name: CI for C Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Install gcc and make
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y gcc make

      # Build the project
      - name: Build
        run: make

      # Run the program
      - name: Test run
        run: ./program